<class 'dataactcore.utils.responseException.ResponseException'>: type object 'User' has no attribute 'email'
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 27, 'register_user', 'user = interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 43, 'getUserByEmail', 'result = self.session.query(User).filter(User.email == email).all()')]
<class 'dataactcore.utils.responseException.ResponseException'>: type object 'User' has no attribute 'email'
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 27, 'register_user', 'user = interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 43, 'getUserByEmail', 'result = self.session.query(User).filter(User.email == email).all()')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 27, 'register_user', 'user = interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 45, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Multiple users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 27, 'register_user', 'user = interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 45, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 76, 'checkUnique', 'raise ResponseException(multipleResultMessage,StatusCode.CLIENT_ERROR,MultipleResultsFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 27, 'register_user', 'user = interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 45, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 27, 'register_user', 'user = interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 48, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 27, 'register_user', 'user = interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 47, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 27, 'register_user', 'user = interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 47, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 27, 'register_user', 'user = interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: email not found
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\utils\\requestDictionary.py', 24, 'getValue', 'raise ValueError(value + " not found")')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: email not found
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\utils\\requestDictionary.py', 24, 'getValue', 'raise ValueError(value + " not found")')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 70, 'changeStatus', 'user.user_status_id = UserStatus.getStatus(statusName)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 57, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 70, 'changeStatus', 'user.user_status_id = UserStatus.getStatus(statusName)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 73, 'changeStatus', 'user.user_status_id = UserStatus.getStatus(statusName)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: <dataactcore.models.userModel.User object at 0x000000000408EBE0> is not JSON serializable
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 55, 'list_users_with_status', 'return accountManager.listUsersWithStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'return JsonResponse.create(StatusCode.OK,{"users":users})'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\utils\\jsonResponse.py', 24, 'create', 'jsondata.set_data(json.dumps(dictionaryData))'), ('C:\\Python27\\lib\\json\\__init__.py', 243, 'dumps', 'return _default_encoder.encode(obj)'), ('C:\\Python27\\lib\\json\\encoder.py', 207, 'encode', 'chunks = self.iterencode(o, _one_shot=True)'), ('C:\\Python27\\lib\\json\\encoder.py', 270, 'iterencode', 'return _iterencode(o, 0)'), ('C:\\Python27\\lib\\json\\encoder.py', 184, 'default', 'raise TypeError(repr(o) + " is not JSON serializable")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: <dataactcore.models.userModel.User object at 0x0000000004100978> is not JSON serializable
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 55, 'list_users_with_status', 'return accountManager.listUsersWithStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'return JsonResponse.create(StatusCode.OK,{"users":users})'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\utils\\jsonResponse.py', 24, 'create', 'jsondata.set_data(json.dumps(dictionaryData))'), ('C:\\Python27\\lib\\json\\__init__.py', 243, 'dumps', 'return _default_encoder.encode(obj)'), ('C:\\Python27\\lib\\json\\encoder.py', 207, 'encode', 'chunks = self.iterencode(o, _one_shot=True)'), ('C:\\Python27\\lib\\json\\encoder.py', 270, 'iterencode', 'return _iterencode(o, 0)'), ('C:\\Python27\\lib\\json\\encoder.py', 184, 'default', 'raise TypeError(repr(o) + " is not JSON serializable")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: <dataactcore.models.userModel.User object at 0x0000000004DF65F8> is not JSON serializable
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 55, 'list_users_with_status', 'return accountManager.listUsersWithStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'return JsonResponse.create(StatusCode.OK,{"users":users})'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\utils\\jsonResponse.py', 24, 'create', 'jsondata.set_data(json.dumps(dictionaryData))'), ('C:\\Python27\\lib\\json\\__init__.py', 243, 'dumps', 'return _default_encoder.encode(obj)'), ('C:\\Python27\\lib\\json\\encoder.py', 207, 'encode', 'chunks = self.iterencode(o, _one_shot=True)'), ('C:\\Python27\\lib\\json\\encoder.py', 270, 'iterencode', 'return _iterencode(o, 0)'), ('C:\\Python27\\lib\\json\\encoder.py', 184, 'default', 'raise TypeError(repr(o) + " is not JSON serializable")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: <dataactcore.models.userModel.User object at 0x0000000003BFBBA8> is not JSON serializable
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 55, 'list_users_with_status', 'return accountManager.listUsersWithStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'return JsonResponse.create(StatusCode.OK,{"users":users})'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\utils\\jsonResponse.py', 24, 'create', 'jsondata.set_data(json.dumps(dictionaryData))'), ('C:\\Python27\\lib\\json\\__init__.py', 243, 'dumps', 'return _default_encoder.encode(obj)'), ('C:\\Python27\\lib\\json\\encoder.py', 207, 'encode', 'chunks = self.iterencode(o, _one_shot=True)'), ('C:\\Python27\\lib\\json\\encoder.py', 270, 'iterencode', 'return _iterencode(o, 0)'), ('C:\\Python27\\lib\\json\\encoder.py', 184, 'default', 'raise TypeError(repr(o) + " is not JSON serializable")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: <dataactcore.models.userModel.User object at 0x0000000004E676D8> is not JSON serializable
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 55, 'list_users_with_status', 'return accountManager.listUsersWithStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'return JsonResponse.create(StatusCode.OK,{"users":users})'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\utils\\jsonResponse.py', 24, 'create', 'jsondata.set_data(json.dumps(dictionaryData))'), ('C:\\Python27\\lib\\json\\__init__.py', 243, 'dumps', 'return _default_encoder.encode(obj)'), ('C:\\Python27\\lib\\json\\encoder.py', 207, 'encode', 'chunks = self.iterencode(o, _one_shot=True)'), ('C:\\Python27\\lib\\json\\encoder.py', 270, 'iterencode', 'return _iterencode(o, 0)'), ('C:\\Python27\\lib\\json\\encoder.py', 184, 'default', 'raise TypeError(repr(o) + " is not JSON serializable")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 55, 'list_users_with_status', 'return accountManager.listUsersWithStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 93, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 93, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 93, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 138, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 106, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 124, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 127, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 139, 'listUsersWithStatus', 'users = self.interfaces.userDb.getUsersByStatus(input.getValue("status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 94, 'getUsersByStatus', 'statusId = UserStatus.getStatus(status)'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\userModel.py', 25, 'getStatus', 'raise ValueError("Not a valid user status")')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 125, 'changeStatus', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("user_email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: No users with that email
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 23, 'register_user', 'return accountManager.register()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 107, 'register', 'user = self.interfaces.userDb.getUserByEmail(input.getValue("email"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 59, 'getUserByEmail', 'self.checkUnique(result,"No users with that email", "Multiple users with that email")'), ('C:\\Users\\jworcest\\Documents\\dataactcore\\dataactcore\\models\\baseInterface.py', 72, 'checkUnique', 'raise ResponseException(noResultMessage,StatusCode.CLIENT_ERROR,NoResultFound,10)')]
<class 'dataactcore.utils.responseException.ResponseException'>: Request body must include email, name, agency, and title
[]
<class 'dataactcore.utils.responseException.ResponseException'>: Not a valid user status
[('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\userRoutes.py', 39, 'change_status', 'return accountManager.changeStatus()'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\accountHandler.py', 128, 'changeStatus', 'self.interfaces.userDb.changeStatus(user,input.getValue("new_status"))'), ('C:\\Users\\jworcest\\Documents\\dataactbroker\\dataactbroker\\handlers\\userHandler.py', 76, 'changeStatus', 'raise ResponseException(str(e),StatusCode.CLIENT_ERROR,ValueError)')]
